/** @type {import('tailwindcss').Config} */
export default {
    content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}', './public/**/*.html'],
    theme: {
        extend: {
            fontSize: {
                xs: ['0.75rem', { lineHeight: '1.25', letterSpacing: '0.025em', fontWeight: '400' }],
                sm: ['0.875rem', { lineHeight: '1.5', letterSpacing: '0.025em', fontWeight: '400' }],
                base: ['1rem', { lineHeight: '1.5', letterSpacing: '0.025em', fontWeight: '400' }],
                lg: ['1.125rem', { lineHeight: '1.75', letterSpacing: '0.025em', fontWeight: '400' }],
                xl: ['1.25rem', { lineHeight: '1.75', letterSpacing: '0.025em', fontWeight: '400' }],
                '2xl': ['1.5rem', { lineHeight: '2', letterSpacing: '0.025em', fontWeight: '500' }],
                '3xl': ['1.875rem', { lineHeight: '2.25', letterSpacing: '0.025em', fontWeight: '500' }],
                '4xl': ['2.25rem', { lineHeight: '2.5', letterSpacing: '0.025em', fontWeight: '500' }],
                '5xl': ['3rem', { lineHeight: '1', letterSpacing: '-0.025em', fontWeight: '700' }],
                '6xl': ['3.75rem', { lineHeight: '1', letterSpacing: '-0.025em', fontWeight: '700' }],
                '7xl': ['4.5rem', { lineHeight: '1', letterSpacing: '-0.025em', fontWeight: '700' }],
                '8xl': ['6rem', { lineHeight: '1', letterSpacing: '-0.025em', fontWeight: '700' }],
                '9xl': ['8rem', { lineHeight: '1', letterSpacing: '-0.025em', fontWeight: '700' }],
            },
            fontFamily: {
                heading: "cormorantgaramond",
                paragraph: "sora-light",
                sans: "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue', sans-serif"
            },
            colors: {
                primary: "#58355E",
                "primary-foreground": "#FFFFFF",
                secondary: "#F5F1EA",
                "secondary-foreground": "#1A1A1A",
                background: "#E8E2D8",
                "primary-bg": "#E8E2D8",
                "secondary-bg": "#F5F1EA",
                "primary-text": "#1A1A1A",
                "secondary-text": "#6E6A64",
                accent: "#111111",
                "light-contrast": "#FFFFFF",
                "emerald-green": "#10B981",
                "slate-blue": "#2E5090",
                gold: "#D4AF37",
                "cta-purple": "#58355E",
                foreground: "#1A1A1A",
                destructive: "#D32F2F",
                "destructive-foreground": "#FFFFFF",
                "off-white": "#E8E2D8",
                "soft-white": "#F5F1EA",
                "warm-bronze": "#58355E",
                "soft-bronze": "#6E6A64",
                "warm-grey": "#6E6A64",
                "charcoal-black": "#1A1A1A",
                "dark-gray": "#58355E",
                "warm-sand-beige": "#E8E2D8",
                white: "#FFFFFF",
                "light-gray": "#F5F1EA",
                "medium-gray": "#6E6A64",
                "rose-blush": "#F5F1EA",
                "soft-lavender": "#F5F1EA",
                "sage-green": "#E8E2D8",
                "accent-blue": "#58355E",
                "accent-teal": "#58355E",
                "warm-cream": "#F5F1EA",
                "cta-buttons": "#58355eff"
            },
        },
    },
    future: {
        hoverOnlyWhenSupported: true,
    },
    plugins: [require('@tailwindcss/container-queries'), require('@tailwindcss/typography')],
}
